version: "3.0"
services:
  core-db:
    build: core-db
    ports:
      - "5433:5432"
  auth-db:
    build: auth-db
    ports:
      - "5432:5432"
  auth:
    build: auth
    ports:
      - "3005:3005"
      - "3006:3006"
    volumes:
      - user-images:/usr/src/app/images
  payment_core:
    build: payment
    ports:
      - "8082:8080"
    volumes:
      - payment-wallet:/root/.PaymentService
      - m2-repo:/root/.m2
#  vault:
#    build: vault
#    ports:
#      - "8081:8081"
#    volumes:
#      - vault-wallet:/root/.Vault
#      - m2-repo:/root/.m2
  core:
    build: core
    ports:
      - "3002:3002"
  jms:
    build: jms
    ports:
      - "3001:3001"
  jmw:
    build: jmw
    ports:
      - "3004:3004"

volumes:
  payment-wallet:
  vault-wallet:
  m2-repo:
  user-images:

networks:
  default:
    external:
      name: iuno-network