version: "3.0"
services:
  auth:
    build: auth
    ports:
      - "3005:3005"
      - "3006:3006"
  core:
      build: core
      ports:
        - "3002:3002"
  jms:
      build: jms
      ports:
        - "3001:3001"
  jmw:
      build: jmw
      ports:
        - "3004:3004"

